export const GET_DRAFTS="GET_DRAFTS";
export const ADD_DRAFTREQUIREMENT="ADD_DRAFTREQUIREMENT";
export const DELETE_DRAFT_REQUIREMENT = "DELETE_DRAFT_REQUIREMENT";
export const GET_TOTALREQUIREMENTS_Draft="GET_TOTALREQUIREMENTS_Draft"