export const GET_SUBSCRIPTION_DATA = "GET_SUBSCRIPTION_DATA ";
export const ADD_SUBSCRIPTION_DATA = "ADD_SUBSCRIPTION_DATA ";
export const GET_SINGLE_SUBSCRIPTION_DATA = "GET_SINGLE_SUBSCRIPTION_DATA ";
export const UPDATE_SINGLE_SUBSCRIPTION_DATA = "UPDATE_SINGLE_SUBSCRIPTION_DATA ";
export const FILTER_USER = "FILTER_USER"
export const SORT_USER = "SORT_USER"
export const DELETE_USER = "DELETE_USER";





