export const GET_SUBSCRIPTION_DATA = "GET_SUBSCRIPTION_DATA ";
export const ADD_SUBSCRIPTION_DATA = "ADD_SUBSCRIPTION_DATA ";
export const GET_SINGLE_SUBSCRIPTION_DATA = "GET_SINGLE_SUBSCRIPTION_DATA ";
export const UPDATE_SINGLE_SUBSCRIPTION_DATA = "UPDATE_SINGLE_SUBSCRIPTION_DATA ";
export const FILTER_SUBCRIPTION_ACTIVE = "FILTER_SUBCRIPTION_ACTIVE"
export const FILTER_SUBCRIPTION_INACTIVE = "FILTER_SUBCRIPTION_INACTIVE"
export const SORT_USER = "SORT_USER"
export const DELETE_USER = "DELETE_USER";





