export const GET_REQUIREMENTS = "GET_REQUIREMENTS";
// export const DELETE_USER = "DELETE_USER";
export const ADD_REQUIREMENT = "ADD_REQUIREMENT";
export const UPDATE_REQUIREMENT = "UPDATE_REQUIREMENT";
export const GET_SINGLE_REQUIREMENT = "GET_SINGLE_REQUIREMENT";
export const FILTER_REQUIREMENT ="FILTER_REQUIREMENT"
export const SORT_REQUIREMENT="SORT_REQUIREMENT"



