export const GET_REQUIREMENTS = "GET_REQUIREMENTS";
export const DELETE_REQUIREMENT = "DELETE_REQUIREMENT";
export const ADD_REQUIREMENT = "ADD_REQUIREMENT";
export const UPDATE_REQUIREMENT = "UPDATE_REQUIREMENT";
export const GET_SINGLE_REQUIREMENT = "GET_SINGLE_REQUIREMENT";
export const FILTER_REQUIREMENT_ACTIVE ="FILTER_REQUIREMENT_ACTIVE"
export const FILTER_REQUIREMENT_INACTIVE ="FILTER_REQUIREMENT_INACTIVE"
export const SORT_REQUIREMENT="SORT_REQUIREMENT"
export const GET_TOTALREQUIREMENTS="GET_TOTALREQUIREMENTS"



